export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  FEEDS: "/feeds",
  TODO: "/todo/review",
  SALARY: "/salary",
  LEAVE_APPLY: "/leave/leave-apply/*",
  Leave_HISTORY_DETAILS:'/leave/leave-apply/history/view-details',
  LEAVE_BALANCES: "/leave/leave-balances",
  LEAVE_CALENDAR: "/leave/leave-calendar",
  HOLIDAY_CALENDAR: "/leave/holiday-calendar",
  DOCUMENT_CENTER: "/document-center",
  PEOPLE: "/people",
  HELPDESK: "/helpdesk",
  WORKFLOW_DELEGATES: "/workflow-delegates",
};
